version: '3.4'

services:
  redis:
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  web:
    build: ./
    container_name: web
    restart: always
    environment:
      - TERM=xterm
      - DJANGO_SETTINGS_MODULE=hrtc.settings
    command: daphne -b 0.0.0.0 -p 5000 hrtc.asgi:application
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf/:/etc/letsencrypt/
      - ./certbot/www/:/var/www/certbot/
    depends_on:
      - web
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf/:/etc/letsencrypt/
      - ./certbot/www/:/var/www/certbot/
    command: certonly --webroot -w /var/www/certbot/ --force-renewal --email dhimanparas20@gmail.com -d hrtc.tech -d www.hrtc.tech --agree-tos  
