# Generated by Django 5.0.6 on 2024-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='exactusername',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
